apiVersion: v1
kind: PersistentVolume
metadata:
  name: statefulset-vol-5
spec:
  capacity:
    storage: "2" # must match "size" parameter below
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn # must be same name that we will use later
  flexVolume:
    driver: "longhorn" # driver must match this
    fsType: "ext4"
    options:
      size: "2"
      staleReplicaTimeout: '30'
      fromBackup: s3://backupbucket@us-east-1/?backup=backup-AAAA&volume=pvc-AAAA

